/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JantinhaTela;

import java.awt.Color;
import java.awt.Cursor;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class tela extends javax.swing.JFrame {

    ImageIcon imgErro = new ImageIcon(getClass().getResource("/Imagens/erro.png"));
    public static float cp[][] = new float[3][1];
    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextAreaSaida.setEditable(false);
    }
    
    public String merroValorArroz(boolean verdade){
        if(verdade){
            return "valor do arroz";
        }else{
            return "";
        }
    }
    
    public String merroValorFeijao(boolean verdade){
        if(verdade){
            return "valor do feijao";
        }else{
            return "";
        }
    }
    
    public String merroValorCarne(boolean verdade){
        if(verdade){
            return "valor da carne";
        }else{
            return "";
        }
    }
    
    public String merroValorSalada(boolean verdade){
        if(verdade){
            return "valor da salada";
        }else{
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextAreaSaida = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldArroz1 = new javax.swing.JTextField();
        jTextFieldFeijao1 = new javax.swing.JTextField();
        jTextFieldCarne1 = new javax.swing.JTextField();
        jTextFieldSalada1 = new javax.swing.JTextField();
        jTextFieldArroz2 = new javax.swing.JTextField();
        jTextFieldArroz3 = new javax.swing.JTextField();
        jTextFieldFeijao2 = new javax.swing.JTextField();
        jTextFieldCarne2 = new javax.swing.JTextField();
        jTextFieldSalada2 = new javax.swing.JTextField();
        jTextFieldFeijao3 = new javax.swing.JTextField();
        jTextFieldCarne3 = new javax.swing.JTextField();
        jTextFieldSalada3 = new javax.swing.JTextField();
        jTextFieldPrecoArroz = new javax.swing.JTextField();
        jTextFieldPrecoFeijao = new javax.swing.JTextField();
        jTextFieldPrecoCarne = new javax.swing.JTextField();
        jTextFieldPrecoSalada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelEnviar = new javax.swing.JPanel();
        jLabelEnviar = new javax.swing.JLabel();
        jPanelTelaVendas = new javax.swing.JPanel();
        jLabelTelaVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jantinha ");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jantinha do Alaô");

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel2.setText("Saída");

        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel3.setText("Preço");

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel4.setText("Quantidade");

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jTextAreaSaida.setRows(5);
        jTextAreaSaida.setText("Prato 1:\nPrato 2:\nPrato 3:");
        jTextAreaSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel5.setText("Feijão");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel6.setText("Arroz");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel7.setText("Carne");

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel8.setText("Salada");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setText("R$");

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setText("R$");

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setText("R$");

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel12.setText("R$");

        jTextFieldArroz1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldArroz1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldArroz1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldArroz1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldArroz1KeyTyped(evt);
            }
        });

        jTextFieldFeijao1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldFeijao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFeijao1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldFeijao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFeijao1KeyTyped(evt);
            }
        });

        jTextFieldCarne1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldCarne1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCarne1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldCarne1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCarne1KeyTyped(evt);
            }
        });

        jTextFieldSalada1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldSalada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalada1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldSalada1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSalada1KeyTyped(evt);
            }
        });

        jTextFieldArroz2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldArroz2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldArroz2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldArroz2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldArroz2KeyTyped(evt);
            }
        });

        jTextFieldArroz3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldArroz3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldArroz3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldArroz3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldArroz3KeyTyped(evt);
            }
        });

        jTextFieldFeijao2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldFeijao2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFeijao2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldFeijao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFeijao2ActionPerformed(evt);
            }
        });
        jTextFieldFeijao2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFeijao2KeyTyped(evt);
            }
        });

        jTextFieldCarne2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldCarne2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCarne2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldCarne2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCarne2KeyTyped(evt);
            }
        });

        jTextFieldSalada2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldSalada2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalada2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldSalada2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSalada2KeyTyped(evt);
            }
        });

        jTextFieldFeijao3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldFeijao3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFeijao3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldFeijao3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFeijao3KeyTyped(evt);
            }
        });

        jTextFieldCarne3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldCarne3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCarne3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldCarne3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCarne3KeyTyped(evt);
            }
        });

        jTextFieldSalada3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldSalada3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalada3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldSalada3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSalada3KeyTyped(evt);
            }
        });

        jTextFieldPrecoArroz.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldPrecoArroz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoArroz.setToolTipText("");
        jTextFieldPrecoArroz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldPrecoArroz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecoArrozKeyTyped(evt);
            }
        });

        jTextFieldPrecoFeijao.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldPrecoFeijao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoFeijao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldPrecoFeijao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecoFeijaoKeyTyped(evt);
            }
        });

        jTextFieldPrecoCarne.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldPrecoCarne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoCarne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldPrecoCarne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecoCarneKeyTyped(evt);
            }
        });

        jTextFieldPrecoSalada.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextFieldPrecoSalada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoSalada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldPrecoSalada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecoSaladaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel13.setText("Arroz");

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel14.setText("Feijão");

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel15.setText("Carne");

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel16.setText("Salada");

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prato 3");

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Prato 1");

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Prato 2");

        jPanelEnviar.setBackground(new java.awt.Color(0, 204, 0));
        jPanelEnviar.setPreferredSize(new java.awt.Dimension(160, 48));
        jPanelEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseExited(evt);
            }
        });

        jLabelEnviar.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabelEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnviar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnviar.setText("Enviar");

        javax.swing.GroupLayout jPanelEnviarLayout = new javax.swing.GroupLayout(jPanelEnviar);
        jPanelEnviar.setLayout(jPanelEnviarLayout);
        jPanelEnviarLayout.setHorizontalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanelEnviarLayout.setVerticalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanelTelaVendas.setBackground(new java.awt.Color(255, 255, 0));
        jPanelTelaVendas.setPreferredSize(new java.awt.Dimension(160, 48));
        jPanelTelaVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTelaVendasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTelaVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTelaVendasMouseExited(evt);
            }
        });

        jLabelTelaVendas.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabelTelaVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelaVendas.setText("Tela de Vendas");

        javax.swing.GroupLayout jPanelTelaVendasLayout = new javax.swing.GroupLayout(jPanelTelaVendas);
        jPanelTelaVendas.setLayout(jPanelTelaVendasLayout);
        jPanelTelaVendasLayout.setHorizontalGroup(
            jPanelTelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTelaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        jPanelTelaVendasLayout.setVerticalGroup(
            jPanelTelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTelaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextAreaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jPanelEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jPanelTelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrecoFeijao))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrecoCarne))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrecoSalada))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrecoArroz, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldArroz1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldArroz2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldArroz3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(353, 353, 353))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(185, 185, 185))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel14)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel15)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel16)
                                    .addGap(30, 30, 30)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldFeijao1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSalada1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldFeijao2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCarne2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSalada2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldFeijao3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCarne3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSalada3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFeijao1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalada1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArroz1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFeijao2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCarne2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalada2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArroz2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFeijao3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCarne3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalada3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArroz3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldPrecoArroz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldPrecoFeijao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldPrecoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldPrecoSalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelTelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAreaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrecoArrozKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecoArrozKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrecoArrozKeyTyped

    private void jTextFieldPrecoFeijaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecoFeijaoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrecoFeijaoKeyTyped

    private void jTextFieldPrecoCarneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCarneKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrecoCarneKeyTyped

    private void jTextFieldPrecoSaladaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecoSaladaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrecoSaladaKeyTyped

    private void jTextFieldArroz1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldArroz1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldArroz1KeyTyped

    private void jTextFieldFeijao1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeijao1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldFeijao1KeyTyped

    private void jTextFieldCarne1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCarne1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCarne1KeyTyped

    private void jTextFieldSalada1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalada1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSalada1KeyTyped

    private void jTextFieldArroz2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldArroz2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldArroz2KeyTyped

    private void jTextFieldFeijao2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeijao2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldFeijao2KeyTyped

    private void jTextFieldCarne2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCarne2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCarne2KeyTyped

    private void jTextFieldSalada2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalada2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSalada2KeyTyped

    private void jTextFieldArroz3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldArroz3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldArroz3KeyTyped

    private void jTextFieldFeijao3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeijao3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldFeijao3KeyTyped

    private void jTextFieldCarne3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCarne3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCarne3KeyTyped

    private void jTextFieldSalada3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalada3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.toString(c).equals(",")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSalada3KeyTyped

    private void jTextFieldFeijao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFeijao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFeijao2ActionPerformed

    private void jPanelEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseClicked
        // TODO add your handling code here:
        String erro = "O ";
        boolean valoresOk = false;
        boolean qtdOk = false;
        
        float ValorArroz = 0, ValorCarne = 0, ValorSalada = 0, ValorFeijao = 0;
        
        boolean erroValorArroz = false; // Erro
        
        /*
        String ValorArroz1 = jTextFieldPrecoArroz.getText();
        ValorArroz1 = ValorArroz1.replace(",", ".");
        ValorArroz = Float.parseFloat(ValorArroz1);*/
        
        try{
            ValorArroz = Float.parseFloat(jTextFieldPrecoArroz.getText().replace(",", "."));
        }catch(NumberFormatException nfe){
            erroValorArroz = true;
        }
        
        boolean erroValorCarne = false;
        
        try{
            ValorCarne = Float.parseFloat(jTextFieldPrecoCarne.getText().replace(",", "."));
        }catch(NumberFormatException nfe){
            erroValorCarne = true;
        }
        
        boolean erroValorSalada = false;
        
        try{
            ValorSalada = Float.parseFloat(jTextFieldPrecoSalada.getText().replace(",", "."));
        }catch(NumberFormatException nfe){
            erroValorSalada = true;
        }
        
        boolean erroValorFeijao = false;
        
        try{
            ValorFeijao = Float.parseFloat(jTextFieldPrecoFeijao.getText().replace(",", "."));
        }catch(NumberFormatException nfe){
            erroValorFeijao = true;
        }
        
        int qtdErro = 0;
        String transf = ""; // String para verificação de método e transferência
        
        if(erroValorArroz || erroValorCarne || erroValorSalada || erroValorFeijao){
            if(erroValorArroz){
                qtdErro++;
            }
            if(erroValorCarne){
                qtdErro++;
            }
            if(erroValorSalada){
                qtdErro++;
            }
            if(erroValorFeijao){
                qtdErro++;
            }
            
            if(qtdErro > 1){ // Se qtdErro for maior que 1
                transf = merroValorArroz(erroValorArroz);
                if(transf.equals("")){
                    
                }else{
                    if(erro.equals("O ")){
                        erro += transf;
                        transf = "";
                    }else{
                        if(qtdErro > 1){
                            erro += ", ";
                        }else{
                            erro += " e  o ";
                        }
                        
                        erro += transf;
                        transf = "";
                        
                    }
                    qtdErro--;
                }
                
                transf = merroValorFeijao(erroValorFeijao);
                if(transf.equals("")){
                    
                }else{
                    if(erro.equals("O ")){
                        erro += transf;
                        transf = "";
                    }else{
                        if(qtdErro > 1){
                            erro += ", ";
                        }else{
                            erro += " e  o ";
                        }
                        
                        erro += transf;
                        transf = "";
                        
                    }
                    qtdErro--;
                }
                
                transf = merroValorCarne(erroValorCarne);
                if(transf.equals("")){
                    
                }else{
                    if(erro.equals("O ")){
                        erro += transf;
                        transf = "";
                    }else{
                        if(qtdErro > 1){
                            erro += ", ";
                        }else{
                            erro += " e o ";
                        }
                        
                        erro += transf;
                        transf = "";
                        
                    }
                    qtdErro--;
                }
                
                transf = merroValorSalada(erroValorSalada);
                if(transf.equals("")){
                    
                }else{
                    if(erro.equals("O ")){
                        erro += transf;
                        transf = "";
                    }else{
                        if(qtdErro > 1){
                            erro += ", ";
                        }else{
                            erro += " e o ";
                        }
                        
                        erro += transf;
                        transf = "";
                        
                    }
                    qtdErro--;
                }
                erro += " não foram preenchidos corretamente.\nPor gentileza corrigir.";
            }else{ // Se qtdErro == 1
                transf += merroValorArroz(erroValorArroz);
                transf += merroValorFeijao(erroValorFeijao);
                transf += merroValorCarne(erroValorCarne);
                transf += merroValorSalada(erroValorSalada);
                erro += transf + " não foi preenchido corretamente.\nPor gentileza corrigir.";
            }
            JOptionPane.showMessageDialog(null, erro, "Erro de valor", JOptionPane.ERROR_MESSAGE, imgErro);
        }else{
            valoresOk = true;
        }
        
        if(valoresOk){

            float QuantidadeArroz1 = 0, QuantidadeArroz2 = 0, QuantidadeArroz3 = 0, 
                    QuantidadeCarne1 = 0, QuantidadeCarne2 = 0, QuantidadeCarne3 = 0, 
                    QuantidadeSalada1 = 0, QuantidadeSalada2 = 0, QuantidadeSalada3 = 0,
                    QuantidadeFeijao1 = 0, QuantidadeFeijao2 = 0, QuantidadeFeijao3 = 0;
            boolean qtderro = false;
            // Try catch Arroz

            try{
                QuantidadeArroz1 = Float.parseFloat(jTextFieldArroz1.getText().replace(",", "."));
                QuantidadeArroz2 = Float.parseFloat(jTextFieldArroz2.getText().replace(",", "."));
                QuantidadeArroz3 = Float.parseFloat(jTextFieldArroz3.getText().replace(",", "."));
                QuantidadeCarne1 = Float.parseFloat(jTextFieldCarne1.getText().replace(",", "."));
                QuantidadeCarne2 = Float.parseFloat(jTextFieldCarne2.getText().replace(",", "."));
                QuantidadeCarne3 = Float.parseFloat(jTextFieldCarne3.getText().replace(",", "."));
                QuantidadeSalada1 = Float.parseFloat(jTextFieldSalada1.getText().replace(",", "."));
                QuantidadeSalada2 = Float.parseFloat(jTextFieldSalada2.getText().replace(",", "."));
                QuantidadeSalada3 = Float.parseFloat(jTextFieldSalada3.getText().replace(",", "."));
                QuantidadeFeijao1 = Float.parseFloat(jTextFieldFeijao1.getText().replace(",", "."));
                QuantidadeFeijao2 = Float.parseFloat(jTextFieldFeijao2.getText().replace(",", "."));
                QuantidadeFeijao3 = Float.parseFloat(jTextFieldFeijao3.getText().replace(",", "."));
            }catch(NumberFormatException nfe){
                qtderro = true;
            }
            
            
            if(qtderro){
                JOptionPane.showMessageDialog(null, "Um número da seção quantidade não foi preenchido corretamente.\nPor gentileza corrigir.", "Erro de quantidade", JOptionPane.ERROR_MESSAGE, imgErro);
            }else{
                int i = 0;
                String saida = "";
                float mc[][] = new float[4][1];
                mc[0][0] = ValorArroz;
                mc[1][0] = ValorFeijao;
                mc[2][0] = ValorCarne;
                mc[3][0] = ValorSalada;
                float mp[][] = new float[3][4];
                mp[0][0] = QuantidadeArroz1;
                mp[1][0] = QuantidadeArroz2;
                mp[2][0] = QuantidadeArroz3;
                mp[0][1] = QuantidadeFeijao1;
                mp[1][1] = QuantidadeFeijao2;
                mp[2][1] = QuantidadeFeijao3;
                mp[0][2] = QuantidadeCarne1;
                mp[1][2] = QuantidadeCarne2;
                mp[2][2] = QuantidadeCarne3;
                mp[0][3] = QuantidadeSalada1;
                mp[1][3] = QuantidadeSalada2;
                mp[2][3] = QuantidadeSalada3;
                cp[0][0] = mp[0][0]*mc[0][0] + mp[0][1]*mc[1][0] + mp[0][2]*mc[2][0] + mp[0][3]*mc[3][0];
                cp[1][0] = mp[1][0]*mc[0][0] + mp[1][1]*mc[1][0] + mp[1][2]*mc[2][0] + mp[1][3]*mc[3][0];
                cp[2][0] = mp[2][0]*mc[0][0] + mp[2][1]*mc[1][0] + mp[2][2]*mc[2][0] + mp[2][3]*mc[3][0];
                
                NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
                
                for(i = 0; i < 3; i++){
                    saida += String.format("Prato "+(i+1)+": R$ %s\n",nf.format(cp[i][0]));
                }
                jTextAreaSaida.setText(saida);
            }
            
        }
        
    }//GEN-LAST:event_jPanelEnviarMouseClicked

    private void jPanelEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseEntered
        // TODO add your handling code here:
        jPanelEnviar.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelEnviar.setBackground(new Color(0,175,0));
    }//GEN-LAST:event_jPanelEnviarMouseEntered

    private void jPanelEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseExited
        // TODO add your handling code here:
        jPanelEnviar.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelEnviar.setBackground(new Color(0,204,0));
    }//GEN-LAST:event_jPanelEnviarMouseExited

    private void jPanelTelaVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTelaVendasMouseClicked
        TelaVendas vendas = new TelaVendas();
        vendas.setVisible(true);
    }//GEN-LAST:event_jPanelTelaVendasMouseClicked

    private void jPanelTelaVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTelaVendasMouseEntered
        // TODO add your handling code here:
        jPanelTelaVendas.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelTelaVendas.setBackground(new Color(255,220,0));
    }//GEN-LAST:event_jPanelTelaVendasMouseEntered

    private void jPanelTelaVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTelaVendasMouseExited
        // TODO add your handling code here:
        jPanelTelaVendas.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelTelaVendas.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_jPanelTelaVendasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEnviar;
    private javax.swing.JLabel jLabelTelaVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEnviar;
    private javax.swing.JPanel jPanelTelaVendas;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldArroz1;
    private javax.swing.JTextField jTextFieldArroz2;
    private javax.swing.JTextField jTextFieldArroz3;
    private javax.swing.JTextField jTextFieldCarne1;
    private javax.swing.JTextField jTextFieldCarne2;
    private javax.swing.JTextField jTextFieldCarne3;
    private javax.swing.JTextField jTextFieldFeijao1;
    private javax.swing.JTextField jTextFieldFeijao2;
    private javax.swing.JTextField jTextFieldFeijao3;
    private javax.swing.JTextField jTextFieldPrecoArroz;
    private javax.swing.JTextField jTextFieldPrecoCarne;
    private javax.swing.JTextField jTextFieldPrecoFeijao;
    private javax.swing.JTextField jTextFieldPrecoSalada;
    private javax.swing.JTextField jTextFieldSalada1;
    private javax.swing.JTextField jTextFieldSalada2;
    private javax.swing.JTextField jTextFieldSalada3;
    // End of variables declaration//GEN-END:variables
}
