/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JantinhaTela;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author ALUNO
 */
public class TelaVendas extends javax.swing.JFrame {
    public int Prato1 = 0;
    public int Prato2 = 0;
    public int Prato3 = 0;
    public int qPrato1 = 0;
    public int qPrato2 = 0;
    public int qPrato3 = 0;
    

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldPrato1 = new javax.swing.JTextField();
        jTextFieldPrato2 = new javax.swing.JTextField();
        jTextFieldPrato3 = new javax.swing.JTextField();
        jPanelmenos1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelmais1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelmais2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelmenos2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelmais3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelConfirmarVenda = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldqPrato1 = new javax.swing.JTextField();
        jTextFieldqPrato2 = new javax.swing.JTextField();
        jTextFieldqPrato3 = new javax.swing.JTextField();
        jPanelmenos3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldvPrato1 = new javax.swing.JTextField();
        jTextFieldvPrato2 = new javax.swing.JTextField();
        jTextFieldvPrato3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelVoltar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Vendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldPrato1.setEditable(false);
        jTextFieldPrato1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldPrato1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrato1.setText("0");
        jTextFieldPrato1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldPrato2.setEditable(false);
        jTextFieldPrato2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldPrato2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrato2.setText("0");
        jTextFieldPrato2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldPrato3.setEditable(false);
        jTextFieldPrato3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldPrato3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrato3.setText("0");
        jTextFieldPrato3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanelmenos1.setBackground(new java.awt.Color(255, 0, 0));
        jPanelmenos1.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmenos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmenos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmenos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmenos1MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("-");
        jLabel8.setMaximumSize(new java.awt.Dimension(8, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(8, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout jPanelmenos1Layout = new javax.swing.GroupLayout(jPanelmenos1);
        jPanelmenos1.setLayout(jPanelmenos1Layout);
        jPanelmenos1Layout.setHorizontalGroup(
            jPanelmenos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmenos1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanelmenos1Layout.setVerticalGroup(
            jPanelmenos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelmais1.setBackground(new java.awt.Color(0, 230, 0));
        jPanelmais1.setForeground(new java.awt.Color(204, 204, 0));
        jPanelmais1.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmais1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmais1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmais1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmais1MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("+");

        javax.swing.GroupLayout jPanelmais1Layout = new javax.swing.GroupLayout(jPanelmais1);
        jPanelmais1.setLayout(jPanelmais1Layout);
        jPanelmais1Layout.setHorizontalGroup(
            jPanelmais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        jPanelmais1Layout.setVerticalGroup(
            jPanelmais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelmais2.setBackground(new java.awt.Color(0, 230, 0));
        jPanelmais2.setForeground(new java.awt.Color(204, 204, 0));
        jPanelmais2.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmais2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmais2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmais2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmais2MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("+");

        javax.swing.GroupLayout jPanelmais2Layout = new javax.swing.GroupLayout(jPanelmais2);
        jPanelmais2.setLayout(jPanelmais2Layout);
        jPanelmais2Layout.setHorizontalGroup(
            jPanelmais2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        jPanelmais2Layout.setVerticalGroup(
            jPanelmais2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelmenos2.setBackground(new java.awt.Color(255, 0, 0));
        jPanelmenos2.setForeground(new java.awt.Color(204, 204, 0));
        jPanelmenos2.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmenos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmenos2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmenos2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmenos2MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout jPanelmenos2Layout = new javax.swing.GroupLayout(jPanelmenos2);
        jPanelmenos2.setLayout(jPanelmenos2Layout);
        jPanelmenos2Layout.setHorizontalGroup(
            jPanelmenos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelmenos2Layout.setVerticalGroup(
            jPanelmenos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelmais3.setBackground(new java.awt.Color(0, 230, 0));
        jPanelmais3.setForeground(new java.awt.Color(204, 204, 0));
        jPanelmais3.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmais3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmais3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmais3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmais3MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("+");

        javax.swing.GroupLayout jPanelmais3Layout = new javax.swing.GroupLayout(jPanelmais3);
        jPanelmais3.setLayout(jPanelmais3Layout);
        jPanelmais3Layout.setHorizontalGroup(
            jPanelmais3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        jPanelmais3Layout.setVerticalGroup(
            jPanelmais3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelConfirmarVenda.setBackground(new java.awt.Color(0, 204, 0));
        jPanelConfirmarVenda.setForeground(new java.awt.Color(204, 204, 0));
        jPanelConfirmarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConfirmarVendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelConfirmarVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelConfirmarVendaMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirmar venda");

        javax.swing.GroupLayout jPanelConfirmarVendaLayout = new javax.swing.GroupLayout(jPanelConfirmarVenda);
        jPanelConfirmarVenda.setLayout(jPanelConfirmarVendaLayout);
        jPanelConfirmarVendaLayout.setHorizontalGroup(
            jPanelConfirmarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        jPanelConfirmarVendaLayout.setVerticalGroup(
            jPanelConfirmarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jTextFieldqPrato1.setEditable(false);
        jTextFieldqPrato1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldqPrato1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldqPrato1.setText("0");
        jTextFieldqPrato1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldqPrato2.setEditable(false);
        jTextFieldqPrato2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldqPrato2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldqPrato2.setText("0");
        jTextFieldqPrato2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldqPrato2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldqPrato2MouseClicked(evt);
            }
        });

        jTextFieldqPrato3.setEditable(false);
        jTextFieldqPrato3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldqPrato3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldqPrato3.setText("0");
        jTextFieldqPrato3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanelmenos3.setBackground(new java.awt.Color(255, 0, 0));
        jPanelmenos3.setForeground(new java.awt.Color(204, 204, 0));
        jPanelmenos3.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanelmenos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelmenos3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelmenos3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelmenos3MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("-");
        jLabel13.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout jPanelmenos3Layout = new javax.swing.GroupLayout(jPanelmenos3);
        jPanelmenos3.setLayout(jPanelmenos3Layout);
        jPanelmenos3Layout.setHorizontalGroup(
            jPanelmenos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelmenos3Layout.setVerticalGroup(
            jPanelmenos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel1.setText("Prato 1");

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel2.setText("Prato 2");

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel3.setText("Prato 3");

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel5.setText("Total Prato 1");

        jTextFieldvPrato1.setEditable(false);
        jTextFieldvPrato1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldvPrato1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldvPrato1.setText("0");
        jTextFieldvPrato1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldvPrato2.setEditable(false);
        jTextFieldvPrato2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldvPrato2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldvPrato2.setText("0");
        jTextFieldvPrato2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldvPrato3.setEditable(false);
        jTextFieldvPrato3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldvPrato3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldvPrato3.setText("0");
        jTextFieldvPrato3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel6.setText("Total Prato 2");

        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel7.setText("Total Prato 3");

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel14.setText("Quantidade");

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel15.setText("Custo");

        jPanelVoltar.setBackground(new java.awt.Color(0, 0, 255));
        jPanelVoltar.setForeground(new java.awt.Color(204, 204, 0));
        jPanelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelVoltarMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Voltar para a tela Principal");

        javax.swing.GroupLayout jPanelVoltarLayout = new javax.swing.GroupLayout(jPanelVoltar);
        jPanelVoltar.setLayout(jPanelVoltarLayout);
        jPanelVoltarLayout.setHorizontalGroup(
            jPanelVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanelVoltarLayout.setVerticalGroup(
            jPanelVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Jantinha do Alaô");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel15)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPrato2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrato1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanelmais3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanelmenos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanelmais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelmais2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanelmenos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldqPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldqPrato2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(jTextFieldqPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldvPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldvPrato2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(jTextFieldvPrato3))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanelConfirmarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldqPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldqPrato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldqPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldvPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldvPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jTextFieldvPrato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanelmais1, 23, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPrato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(jPanelmais2, 23, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelmenos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelmais3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jPanelmenos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConfirmarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelmais1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais1MouseClicked
        Prato1++;
        jTextFieldPrato1.setText(""+Prato1);
    }//GEN-LAST:event_jPanelmais1MouseClicked

    private void jPanelmenos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos1MouseClicked
        if(Prato1 > 0){
            Prato1--;
            jTextFieldPrato1.setText(""+Prato1);
        }
    }//GEN-LAST:event_jPanelmenos1MouseClicked

    private void jPanelmais2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais2MouseClicked
        Prato2++;
        jTextFieldPrato2.setText(""+Prato2);
    }//GEN-LAST:event_jPanelmais2MouseClicked

    private void jPanelmenos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos2MouseClicked
        if(Prato2 > 0){
            Prato2--;
            jTextFieldPrato2.setText(""+Prato2);
        }
    }//GEN-LAST:event_jPanelmenos2MouseClicked

    private void jPanelmais3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais3MouseClicked
        Prato3++;
        jTextFieldPrato3.setText(""+Prato3);
    }//GEN-LAST:event_jPanelmais3MouseClicked

    private void jPanelmenos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos3MouseClicked
        if(Prato3 > 0){
            Prato3--;
            jTextFieldPrato3.setText(""+Prato3);
        }
    }//GEN-LAST:event_jPanelmenos3MouseClicked

    private void jPanelConfirmarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfirmarVendaMouseClicked
        qPrato1 += Prato1;
        qPrato2 += Prato2;
        qPrato3 += Prato3;
        jTextFieldqPrato1.setText(""+qPrato1);
        jTextFieldqPrato2.setText(""+qPrato2);
        jTextFieldqPrato3.setText(""+qPrato3);
        
        String saidavPrato1 = String.format("%.2f", tela.cp[0][0] * qPrato1);
        String saidavPrato2 = String.format("%.2f", tela.cp[1][0]*qPrato2);
        String saidavPrato3 = String.format("%.2f", tela.cp[2][0]*qPrato3);
        jTextFieldvPrato1.setText(saidavPrato1);
        jTextFieldvPrato2.setText(saidavPrato2);
        jTextFieldvPrato3.setText(saidavPrato3);
        Prato1 = 0;
        Prato2 = 0;
        Prato3 = 0;
        jTextFieldPrato1.setText(""+Prato1);
        jTextFieldPrato2.setText(""+Prato2);
        jTextFieldPrato3.setText(""+Prato3);
    }//GEN-LAST:event_jPanelConfirmarVendaMouseClicked

    private void jTextFieldqPrato2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldqPrato2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldqPrato2MouseClicked

    private void jPanelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVoltarMouseClicked
        dispose();
    }//GEN-LAST:event_jPanelVoltarMouseClicked

    private void jPanelConfirmarVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfirmarVendaMouseEntered
        // TODO add your handling code here:
        jPanelConfirmarVenda.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelConfirmarVenda.setBackground(new Color(0,175,0));
    }//GEN-LAST:event_jPanelConfirmarVendaMouseEntered

    private void jPanelConfirmarVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfirmarVendaMouseExited
        // TODO add your handling code here:
        jPanelConfirmarVenda.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelConfirmarVenda.setBackground(new Color(0,204,0));
    }//GEN-LAST:event_jPanelConfirmarVendaMouseExited

    private void jPanelVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVoltarMouseEntered
        // TODO add your handling code here:
        jPanelVoltar.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelVoltar.setBackground(new Color(50,50,255));
    }//GEN-LAST:event_jPanelVoltarMouseEntered

    private void jPanelVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVoltarMouseExited
        // TODO add your handling code here:
        jPanelVoltar.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelVoltar.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_jPanelVoltarMouseExited

    private void jPanelmais1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais1MouseEntered
        // TODO add your handling code here:
        jPanelmais1.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmais1.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_jPanelmais1MouseEntered

    private void jPanelmais1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais1MouseExited
        // TODO add your handling code here:
        jPanelmais1.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelmais1.setBackground(new Color(0,230,0));
    }//GEN-LAST:event_jPanelmais1MouseExited

    private void jPanelmenos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos1MouseEntered
        // TODO add your handling code here:
        jPanelmenos1.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos1.setBackground(new Color(255,75,75));
    }//GEN-LAST:event_jPanelmenos1MouseEntered

    private void jPanelmenos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos1MouseExited
        // TODO add your handling code here:
        jPanelmenos1.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos1.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jPanelmenos1MouseExited

    private void jPanelmais2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais2MouseEntered
        // TODO add your handling code here:
        jPanelmais2.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmais2.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_jPanelmais2MouseEntered

    private void jPanelmais2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais2MouseExited
        // TODO add your handling code here:
        jPanelmais2.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelmais2.setBackground(new Color(0,230,0));
    }//GEN-LAST:event_jPanelmais2MouseExited

    private void jPanelmais3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais3MouseEntered
        // TODO add your handling code here:
        jPanelmais3.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmais3.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_jPanelmais3MouseEntered

    private void jPanelmais3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmais3MouseExited
        // TODO add your handling code here:
        jPanelmais3.setCursor(Cursor.getPredefinedCursor(DEFAULT_CURSOR));
        jPanelmais3.setBackground(new Color(0,230,0));
    }//GEN-LAST:event_jPanelmais3MouseExited

    private void jPanelmenos2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos2MouseEntered
        // TODO add your handling code here:
        jPanelmenos2.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos2.setBackground(new Color(255,75,75));
    }//GEN-LAST:event_jPanelmenos2MouseEntered

    private void jPanelmenos2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos2MouseExited
        // TODO add your handling code here:
        jPanelmenos2.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos2.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jPanelmenos2MouseExited

    private void jPanelmenos3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos3MouseEntered
        // TODO add your handling code here:
        jPanelmenos3.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos3.setBackground(new Color(255,75,75));
    }//GEN-LAST:event_jPanelmenos3MouseEntered

    private void jPanelmenos3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelmenos3MouseExited
        // TODO add your handling code here:
        jPanelmenos3.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
        jPanelmenos3.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jPanelmenos3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConfirmarVenda;
    private javax.swing.JPanel jPanelVoltar;
    private javax.swing.JPanel jPanelmais1;
    private javax.swing.JPanel jPanelmais2;
    private javax.swing.JPanel jPanelmais3;
    private javax.swing.JPanel jPanelmenos1;
    private javax.swing.JPanel jPanelmenos2;
    private javax.swing.JPanel jPanelmenos3;
    private javax.swing.JTextField jTextFieldPrato1;
    private javax.swing.JTextField jTextFieldPrato2;
    private javax.swing.JTextField jTextFieldPrato3;
    private javax.swing.JTextField jTextFieldqPrato1;
    private javax.swing.JTextField jTextFieldqPrato2;
    private javax.swing.JTextField jTextFieldqPrato3;
    private javax.swing.JTextField jTextFieldvPrato1;
    private javax.swing.JTextField jTextFieldvPrato2;
    private javax.swing.JTextField jTextFieldvPrato3;
    // End of variables declaration//GEN-END:variables
}
